# Generated by Django 5.0.2 on 2024-03-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
