# Generated by Django 5.0.2 on 2024-03-09 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount_in_words', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('charge_to_account', models.CharField(blank=True, max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('received_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('cashier_signature', models.ImageField(blank=True, null=True, upload_to='cashier_signatures/')),
                ('receiver_signature', models.ImageField(blank=True, null=True, upload_to='receiver_signatures/')),
                ('voucher_number', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('supervisor_approval_date', models.DateTimeField(blank=True, null=True)),
                ('phase', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Pending Supervisor Approval', 'Pending Supervisor Approval'), ('Pending Approver Approval', 'Pending Approver Approval'), ('Business Approval 1', 'Business Approval 1'), ('Business Approval 2', 'Business Approval 2'), ('Business Approval 3', 'Business Approval 3'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Cash Out', 'Cash Out')], default='Pending Supervisor Approval', max_length=30)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.department')),
                ('forwarded_to_cashier_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_requisitions', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_requisitions', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_requisitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
